version: "3.8"

services:
    keycloak:
      image: jboss/keycloak:12.0.4
      ports: 
        - 8080:8080      
      environment: 
        - KEYCLOAK_USER=${kcadmin}
        - KEYCLOAK_PASSWORD=${kcadmin_password}
        - DB_VENDOR=h2
      volumes:
        - $PWD/kcdb:/opt/jboss/keycloak/standalone/data
      restart: always
