version: '3'

services:
  redismod:
    image: "redislabs/redismod"
    env_file: redis.env
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379